# Prometheus Configuration for AI-Native ATS

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "ai-ats-monitor"

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Backend API metrics
  - job_name: "backend-api"
    static_configs:
      - targets: ["backend:3001"]
    metrics_path: "/api/metrics"
    scrape_interval: 30s

  # Frontend metrics
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:3000"]
    metrics_path: "/api/metrics"
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Nginx metrics
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  # Docker metrics
  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]
